<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>661b099e-b242-42f7-ab23-7283ab735534</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Azure.Data.Tables" Version="12.11.0" />
    <PackageReference Include="Azure.Storage.Blobs" Version="12.29.1" />
    <PackageReference Include="Azure.Storage.Files.Shares" Version="12.27.1" />
    <PackageReference Include="Azure.Storage.Queues" Version="12.27.1" />
  </ItemGroup>

</Project>
